package com.java;
public class exception {
    public static void main(String[] args) {
        try {

            int result = divide(10, 0);
            System.out.println("Result: " + result);
        } catch (ArithmeticException e) {
            System.out.println("Error: Division by zero occurred.");
        }
    }
    

    public static int divide(int dividend, int divisor) {
        return dividend / divisor;
    }
}

Output::
Error: Division by zero occurred.
